### ISSUE TITLE
bmx6 using tinc tunneling instead of gateway

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/firmware#1]
BMX6 can tunnel internet over tinc instead of using the gateway directly. This results in very slow internet connections. We need to tell bmx6 that tinc is slow so it uses gateways correctly.

This was an issue with dba where the access point would use the tinc tunnel through the N750 to Winston's connection instead of using the N750 gateway directly.

This command on N750 fixed the dba problem-
bmx6 -c -i tap0 /rateMax 10000 /rateMin 10000

**Comment by sycophantic** [comment]
Added to check_tunnel.sh
