### ISSUE TITLE
nodog tokens do not match

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/firmware#5]
If I leave mac connected to N600 overnight, in the morning there will be a nodog splash, but when I click on it, splash goes away and I get attached error screen. Attempting to use internet again gives another splash which works normally.
<img width="902" alt="nodog-tokens-dont-match" src="https://cloud.githubusercontent.com/assets/1037006/9699407/a848c924-53af-11e5-9283-8bb291da715b.png">

**Comment by sycophantic** [comment]
We need to set 'clientidletimeout' and 'clientidletimeout' properly.

**Comment by bhny** [comment]
splash screen was from direct connection. Problem is the screen shown is not recognized as nodog is ready to show a new screen. Could be solved by redirect on splash after x minutes. Also we should increase timeout on nodog to 1 day as splash is annoying.

**Comment by sycophantic** [comment]
I checked the nodog source, the values have to be '> 1', it's an int, so we can set it big.

**Comment by sycophantic** [comment]
New image will address the timeouts.
